@uri = http://localhost:12480


### setup db
GET {{uri}}/setup/db?password=12 HTTP/1.1


### change password
GET {{uri}}/setup/db/password?old-password=1234&new-password=12345 HTTP/1.1


### add pay account
POST {{uri}}/account HTTP/1.1
Content-Type: application/json

{
    "account-name": "우리카드",
    "pay-type": "hybrid",
    "repay-day": "12",
    "description": "주 카드"
}

### add pay account
POST {{uri}}/account HTTP/1.1
Content-Type: application/json

{
    "account-name": "리리카드",
    "pay-type": "direct",
    "repay-day": "",
    "description": ""
}

### delete pay account
DELETE {{uri}}/account?id=account:1721395333 HTTP/1.1

### update pay account
PUT {{uri}}/account?id=account:1721395333 HTTP/1.1
Content-Type: application/json

{
    "account-name": "KB체크카드",
    "pay-type": "direct",
    "repay-day": "",
    "description": "주 카드"
}

### get pay account list
GET {{uri}}/account HTTP/1.1



### add category
POST {{uri}}/category HTTP/1.1
Content-Type: application/json

{
    "category-name": "식비"
}

### delete category
DELETE {{uri}}/category?id=category:1721731337 HTTP/1.1

### update pay account
PUT {{uri}}/category?id=category:1721731337 HTTP/1.1
Content-Type: application/json

{
    "category-name": "점심"
}

### get category list
GET {{uri}}/category HTTP/1.1



### add payment
POST {{uri}}/record HTTP/1.1
Content-Type: application/json

{
    "transaction-type": "record_type_pay",
    "account-id": "account:1721563179",
    "pay-type": "direct",
    "currency": "KRW",
    "amount": 10000,
    "category": "식비",
    "description": "아침 식사",
    "date": "2024-07-17",
    "time": "08:27"
}

### add payment
POST {{uri}}/record HTTP/1.1
Content-Type: application/json

{
    "transaction-type": "record_type_pay",
    "pay-type": "credit",
    "currency": "KRW",
    "amount": 13000,
    "category": "식비",
    "description": "점심 식사",
    "date": "2024-07-16",
    "time": "12:35"
}

### add income
POST {{uri}}/record HTTP/1.1
Content-Type: application/json

{
    "transaction-type": "record_type_income",
    "pay-type": "direct",
    "currency": "KRW",
    "amount": 50000,
    "category": "수입",
    "description": "점심 용돈",
    "date": "2024-07-16",
    "time": "13:01"
}

### delete
DELETE {{uri}}/record?id=record:1721190212 HTTP/1.1

### update
PUT {{uri}}/record?id=record:1721577778 HTTP/1.1
Content-Type: application/json

{
    "id": "record:1721577778",
    "transaction-type": "record_type_pay",
    "account-id": "account:1721566319",
    "pay-type": "direct",
    "currency": "KRW",
    "amount": 12500,
    "category": "식비",
    "description": "아점",
    "date": "2024-07-15",
    "time": "11:20"
}

### get record list
GET {{uri}}/record?q=record:&from=2024-05-01&to=2024-08-10 HTTP/1.1

### get record list pays only
GET {{uri}}/record?q=record_type_pay&queryType=AND&from=2024-05-01&to=2024-08-09 HTTP/1.1

### get record list incomes only
GET {{uri}}/record?q=record_type_income&queryType=AND&from=2024-05-01&to=2024-08-09 HTTP/1.1

### search
GET {{uri}}/record?q=record_type_pay%20아침&queryType=AND&from=2024-05-01&to=2024-08-09 HTTP/1.1
