@uri = http://localhost:8080


### init db
GET {{uri}}/setup/db?password=12345 HTTP/1.1

### input - payment
POST {{uri}}/record HTTP/1.1
Content-Type: application/json

{
    "trade-type": "record_type_pay",
    "pay-method": "체크카드",
    "currency": "KRW",
    "amount": 10000,
    "category": "식비",
    "description": "아침 식사",
    "date": "2024-07-17",
    "time": "08:27"
}

### input - payment
POST {{uri}}/record HTTP/1.1
Content-Type: application/json

{
    "trade-type": "record_type_pay",
    "pay-method": "신용카드",
    "currency": "KRW",
    "amount": 13000,
    "category": "식비",
    "description": "점심 식사",
    "date": "2024-07-17",
    "time": "12:35"
}

### input - income
POST {{uri}}/record HTTP/1.1
Content-Type: application/json

{
    "trade-type": "record_type_income",
    "pay-method": "현금",
    "currency": "KRW",
    "amount": 50000,
    "category": "수입",
    "description": "점심 용돈",
    "date": "2024-07-17",
    "time": "13:01"
}

### get list
GET {{uri}}/record/search?q=record_type_pay HTTP/1.1

### search
GET {{uri}}/record/search?q=record_type_pay%20점심&queryType=AND&page=1&pageSize=2 HTTP/1.1

### summary by period
GET {{uri}}/record/sum?start=2024-07-01&end=2024-07-31 HTTP/1.1

### delete
DELETE {{uri}}/record/delete?id=record:1721190212 HTTP/1.1

### update
PUT {{uri}}/record/update?id=record:1721190444 HTTP/1.1
Content-Type: application/json

{
    "type": "record_type_pay",
    "pay-method": "현금",
    "currency": "KRW",
    "amount": 12500,
    "category": "식비",
    "description": "아점",
    "date": "2024-07-17",
    "time": "11:20"
}
